### ISSUE TITLE
relate (0 <..< 1) (0 <=..<= 1) should be During

### ISSUE THREAD

**Issue by Bodigrim** [msakai/data-interval#29] opened 2021-08-23 06:26 UTC
```haskell
> relate (0 <..< 1) (0 <=..<= 1)
Starts
```

My understanding is that this should return `During` instead. CC @marcosh

**Comment by marcosh** [comment] 2021-08-23 06:28
I think you are right, This week I'm on vacation. Next week I'll take a look at it

**Comment by marcosh** [comment] 2021-08-30 06:45
@bodigrim the issue is due to how we currently compare the boundaries of the intervals (using `lowerBound` and `upperBound`). This should be fixed using `lowerBound'` and `upperBound'` but it actually isn't because `relate (NegInf <..< PosInf) (NegInf <=..<= PosInf) == Equal`.

I suspect the most elegant solution would be to introduce a new datatype to represent the boundaries of an interval. Instead of using `(Extended r, Bounday)` it would be nice to have

```haskell
data IntervalBoundary
    = NegInf
    | PosInf
    | Finite r Boundary
```

This way we could avoid issues comparing `(NegInf, Open)` and `(NegInf, Closed)`.

What do you say?

**Comment by Bodigrim** [comment] 2021-08-30 17:28
@marcosh I'm a bit reluctant to introduce an intermediary type. Could we possibly express `relate` directly by pattern-matching on `Interval` constructors?

https://github.com/msakai/data-interval/blob/2755db4543de8c61a1bfe881f42085109114db7f/src/Data/Interval/Internal.hs#L44-L57

**Closed as completed** 2021-09-03 19:26 UTC
